---
title: 异常泛型
order: 3
copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0协议</a>
---

## 异常

异常是继承Throwble类的Exception和Error

- Throwble
  - Error：OutOfMemoryError、NoClassDefFoundError
  - Exception
    - Checked Exception：程序不处理（catch-throw）不能通过编译；FileNotFoundException
    - Unchecked Exception：RuntimeException及其子类（NullPointerException、ArrayIndexOutOfBoundsException）



### 常用方法

- getMessage()
- toString()
- printStackTrace()
- getLocalizedMessage()



### try-catch-finally的执行情况

- try-catch
- try-finally

`finally`：

- 无论是否捕获或处理异常，`finally` 块里的语句都会被执行，除非finally 之前虚拟机被终止运行，比如在catch中程序中断（System.exit(1);）程序所在的线程死亡；关闭 CPU
- 在 `try` 块或 `catch` 块中有 `return` 语句时，先执行`finally` 语句块再执行return
- 不要在finally中用return：如果finally中有return，try中的return语句会被忽略，返回finally中的值



面对异常有两种处理：

1. 抛出不catch处理：throw，方法上是throws
2. catch处理；抛出最终也会处理，如果自己没有写代码处理，就是JVM最后catch并处理



## 泛型**Generics**

编译器对泛型参数进行检测、自动转换为目标对象

静态方法无法使用类中的泛型，因为静态方法的加载优先于类的实例化

